name: 'PowerShell Tests'

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

trigger:
  branches:
    include:
      - '*'
  paths:
    exclude:
      - .github/
      - LICENSE
      - README.md

steps:
  # ref: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops
  - task: PowerShell@2
    displayName: 'Run PowerShell Pest Tests'
    inputs:
      filePath: $(System.DefaultWorkingDirectory)/Pester.ps1
      arguments: '-ModulePath ./ -ResultsPath ./results -Publish'
      errorActionPreference: 'silentlyContinue'
      ignoreLASTEXITCODE: true

  # ref: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish Code Coverage'
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: '**/Pester-Coverage.xml'
      pathToSources: '$(System.DefaultWorkingDirectory)'
      failIfCoverageEmpty: true
      additionalCodeCoverageFiles: '$(System.DefaultWorkingDirectory)/**/*.ps*'

  # ref: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=trx%2Cyaml
  - task: PublishTestResults@2
    displayName: 'Publish Pester Tests'
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: '**/Test-Pester.xml'
      mergeTestResults: true
      failTaskOnFailedTests: true
