name: Test PowerShell on Ubuntu
on: push

jobs:
  pester-test:
    name: Get-Planet Pester Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Perform a Pester test from the command-line
        shell: pwsh
        run: Test-Path resultsfile.log | Should -Be $true
      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
          Invoke-Pester ./GitHub-Actions/Get-Planet.Tests.ps1 -Passthru