name: PowerShell Unit Tests on Ubuntu
on:
  push:
    paths:
      - '.github/workflows/powershell-actions.yml'  # This workflow
      - '**.ps1'

jobs:
  pester-test:
    name: Run PowerShell Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run all Unit Tests
        shell: pwsh
        run: |
          Invoke-Pester -Path ./* -Passthru
