name: Test PowerShell on Ubuntu
on:
  push:
    paths:
      - '**.ps1'

jobs:
  pester-test:
    name: Get-Planet Pester Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Perform PowerShelll Unit Tests
        shell: pwsh
        run: |
          Invoke-Pester -Path ./* -Passthru